# permissions for end users to edit clustertokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: github-token-manager
    app.kubernetes.io/managed-by: kustomize
  name: clustertoken-editor-role
rules:
  - apiGroups:
      - github.as-code.io
    resources:
      - clustertokens
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - github.as-code.io
    resources:
      - clustertokens/status
    verbs:
      - get
