---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.as-code.io
  resources:
  - clustertokens
  - tokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.as-code.io
  resources:
  - clustertokens/finalizers
  - tokens/finalizers
  verbs:
  - update
- apiGroups:
  - github.as-code.io
  resources:
  - clustertokens/status
  - tokens/status
  verbs:
  - get
  - patch
  - update
