# permissions for end users to view tokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: github-token-manager
    app.kubernetes.io/managed-by: kustomize
  name: token-viewer-role
rules:
  - apiGroups:
      - github.as-code.io
    resources:
      - tokens
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - github.as-code.io
    resources:
      - tokens/status
    verbs:
      - get
