{{- if ne (int .Values.config.app_id) 0 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gtm-config
  {{- with (default dict .Values.commonAnnotations) }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    component: deployment
    {{- include "labels" . | nindent 4 }}
stringData:
  gtm.yaml: |
    app_id: {{ .Values.config.app_id | int }}
    installation_id: {{ .Values.config.installation_id | int }}
    provider: "{{ .Values.config.provider }}"
  {{- if ne .Values.config.provider "file" }}
    key: "{{ .Values.config.key }}"
  {{- else }}
    key: /config/private.key
  private.key: |
    {{- .Values.config.key | nindent 4 }}
  {{- end }}
{{- end }}
