{{- if .Values.config.app_id != 0 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gtm-config
  {{- with .Values.commonAnnotations | default dict }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    component: deployment
    {{- include "labels" . | nindent 4 }}
stringData:
  gtm.yaml: |
    app_id: {{ .Values.config.app_id | int }}
    installation_id: {{ .Values.config.installation_id | int }}
    provider: "{{ .Values.config.provider }}"
    key: "{{ .Values.config.key }}"
{{- end }}
